### ISSUE TITLE
Test login.gov Implementation

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/getgov#149]
Once we have Login.gov integration deployed onto our Cloud.gov spaces, we should have people manually test it out. For this ticket:

- [x] Get main deployed and working
- [x] Compose a checklist for what people should do with the app
- [x] Post on Slack a link to the app and the checklist

**Comment by neilmb** [comment]
To QA the Login.gov process:

- [ ] Visit getgov-unstable.app.cloud.gov
- [ ] Click on "Sign in"
- [ ] If you have an account on the Login.gov SANDBOX, use it now.
- [ ] Otherwise, create a new account with the Login.gov SANDBOX. The account must be identity-proofed, just send any old image file for your ID. Make up a FAKE SSN. You will need a REAL telephone number where you can verify that number.
- [ ] You should be taken back to getgov-unstable.app.cloud.gov
- [ ] Click on your "username" which is absurd UUID that we got from Login.
- [ ] What information do you see on that page?
- [ ] Click on the link that says "Click here to log out."
- [ ] You should be taken back to getgov-unstable.app.cloud.gov
