### ISSUE TITLE
Remove the "Type of work" question until we have a controlled list of values

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/getgov#446]
Slack thread: https://gsa-tts.slack.com/archives/C03QM0JGSQG/p1677702708763699

**Acceptance Criteria**

- Remove the type of work question
- Replace with "About your organization..." question. [Updated text to replace "Type of work."](https://docs.google.com/document/d/1GTTeRvKfe3lA_w2U4X_CBk8Q7BpMe7W0m_eVZsTHzEE/edit#heading=h.3whwml4)

Related to https://github.com/cisagov/getgov/issues/447

**Comment by h-m-f-t** [comment]
@gabydisarli Check out the section "Types of Local Government" on pdf pages 9-13 of https://www.census.gov/content/dam/Census/library/publications/2017/econ/2017isd.pdf. This does not include federal agencies or tribal government, but page 11 has a nice breakdown of special districts.

**Comment by gabydisarli** [comment]
Thanks @h-m-f-t !

Since this issue is about removing the question I'm going to refrain from commenting too much on how we implement the question and dropdown in the future. For future record I'm pasting that list you linked here.

Air transportation (airports)
Cemeteries
Corrections
Education
Electric power
Fire protection
Gas supply
Health
Highways
Hospitals
Housing and community development
Industrial development
Libraries
Mortgage credit
Natural resources
Parking facilities
Parks and recreation
Sea and inland port facilities
Sewerage
Solid waste management
Transit
Water supply

**Comment by h-m-f-t** [comment]
(Ah, I see replying on mobile failed me. I should have added this to #447.)
