### ISSUE TITLE
Draft domain request rejection notices with specific explanations

### ISSUE THREAD

**Issue by michelle-rago** [cisagov/getgov#608]
Develop a set of rejection reasons that could be used in notification emails and elsewhere. Examples include:

- [x] Develop a set of reasons for rejections (linked below)
- [x] Create tickets for corresponding rejection language for 
  - #965 
  - #966 
  - #967
  - #968
  - #969
  - #970

Examples:
- Requestor isn't authorized to make the request
- Org isn't eligible for a .gov
- Domain not approved
- AO doesn't approve

### Rejection Reasons
[List of Rejection Reasons Sheet](https://docs.google.com/document/d/1fRJOxz_40FBcBDhHhmdwHrM1o-0BP6eqTCgn2SO68Fg/edit?usp=sharing)

**Comment by kitsushadow** [comment]
relates to #443

**Comment by kitsushadow** [comment]
Tentative AC is to identify if there is canned types of rejection language, like for the above, or do we need something more general, like a text box AND confirm if this is MVP. (Likely yes but need confirmation)

**Comment by gabydisarli** [comment]
@h-m-f-t For the above ticket can you shed light on the additional rejection notices needed? Michelle listed a few above, and there are some sample reasons in the linked Google Doc. Trying to understand the ask here. Are there additional ones we need to supply? Also there is Mohammad's note above.

**Comment by h-m-f-t** [comment]
Thanks @gabydisarli. This is probably worth a short chat in product huddle. 

Right now, rejected requests get a bespoke, human-crafted email manually sent by an analyst (in addition to an automated email from the registrar simply stating the request was rejected). We'd like to have an analyst be able to selected the "Rejected" status while also selecting a reason for the rejection, which should kick off a notification to the registrant that offers an explanation and gives direction (where applicable). 

This issue is about crafting the words in that email for various rejection states. The drafts at that link are not especially great and could certainly be revised/rewritten. 

Is that helpful?

**Comment by h-m-f-t** [comment]
Also, this is not required for MVP.

**Comment by gabydisarli** [comment]
I've received some sample language from Alex & Amera and am mapping some of that language to a google sheet to track all the rejection reasons. I'm waiting on a response to get some more details about these reasons. Next steps after getting the details will be to revise the copy and create the email drafts that can be fed into the automated system.

**Comment by gabydisarli** [comment]
Draft ready for review for: 
[Email_domain request rejected: naming requirements not met](https://docs.google.com/document/d/1vqLpuYlJAFbkplPH6Hm45E0WiQ_ZpVWtInctUT-8fLg/edit?usp=sharing)

**Comment by gabydisarli** [comment]
marked completed as set of reasons has been defined and tickets for draft emails for all reasons have been ticketed
