### ISSUE TITLE
NIST 800-53 family study groups

### ISSUE THREAD

**Issue by colinmurphy01** [cisagov/getgov#67]
# Background

We want to conduct 800-53 study groups for developers and those interested in helping document our ATO. These will be centered around the [800-53 rev 5 family groups](https://controlfreak.risk-redux.io/families). We will want through a set of controls within that family and document any known complications or issues.

**Comment by calerubensteingsa** [comment]
11/28:

Not ready to officially document controls, do we have a rough idea of what to pre-select, yes.

Can we get list of what to pre-select? Some exist in SSPs. Because it's cloud based in AWS cloud, cloud.gov is going to offer majority of inheritance.

Do we have set of common controls we inherit? We have asked, response has been EA has a 3-5 year plan. No. We'll get non-technical things.
